apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hsedemo
  name: hsedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsedemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hsedemo
    spec:
      containers:
      - image: sschanz/distributedsystemshse:KubernetesDemo_v2
        name: distributedsystemshse
        resources: {}
status: {}
