FROM ubuntu:20.10
RUN apt update && apt install openjdk-11-jre-headless -y
RUN mkdir -p /opt/CRUDController
WORKDIR /opt/CRUDController
COPY target/CRUDController-0.0.1-SNAPSHOT.jar /opt/CRUDController
CMD ["java", "-jar", "CRUDController-0.0.1-SNAPSHOT.jar" ]
